
// Manage Generic Actions
export const NEW_DEVICE = 'NEW_DEVICE';
export const UPDATE_DEVICE_START = "UPDATE_DEVICE_START";
export const UPDATE_DEVICE_SUCCESS = "UPDATE_DEVICE_SUCCESS";
export const UPDATE_DEVICE_FAIL = "UPDATE_DEVICE_FAIL";
export const LOAD_DEVICE_START = "LOAD_DEVICE_START";
export const LOAD_DEVICE_SUCCESS = "LOAD_DEVICE_SUCCESS";
export const LOAD_DEVICE_FAIL = "LOAD_DEVICE_FAIL"
export const NEW_ESP32_METRIC = 'NEW_ESP32_METRIC';
export const NEW_NANO_METRIC = 'NEW_NANO_METRIC';
export const GET_HISTORY_INFO = 'GET_HISTORY_INFO'
export const GET_HISTORY_DATA = "GET_HISTORY_DATA"